version: "3.8"

name: "csc302-lint"

services:
  backend:
    container_name: backend-lint
    build:
      context: ./backend
      dockerfile: Dockerfile.lint
      args:
        workdir: /app
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend-lint
    build:
      context: ./frontend
      dockerfile: Dockerfile.lint
      args:
        workdir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/

volumes:
  node_modules: