version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        workdir: /app
    # environment:
    #   FLASK_DEBUG: 1
    #   FLASK_APP: app/app.py
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        workdir: /app
    ports: [ '5000:5000' ]
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules/
