version: "3.8"

name: "csc302-tests"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.test
      args:
        workdir: /app
    # environment:
    #   PYTHONPATH: /app
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
      args:
        workdir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules/
