version: "3.8"

name: "csc302-tests"

services:
  backend:
    container_name: backend-tests
    build:
      context: ./backend
      dockerfile: Dockerfile.test
      args:
        workdir: /app
    volumes:
      - ./backend:/app
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - USING_DOCKER=true

  frontend:
    container_name: frontend-tests
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
      args:
        workdir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/

volumes:
  node_modules: