version: "3.8"

services:
  backend:
    container_name: backend
    build: /backend

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app/app.py
    ports: ['5000:5000']
    volumes:
      - ./frontend:/app