version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        workdir: /app
    ports: [ '5050:5050' ]
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: src/main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5050
      CLIENT_ID: 77b019360235410f81c0904a4ace93ba
      CLIENT_SECRET: a90e38621cae4a6797a97004abe633b8
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        workdir: /app
    ports: [ '5000:5000' ]
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/

volumes:
  node_modules: