# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster

ARG workdir=

WORKDIR ${workdir}

COPY requirements.txt requirements.txt
RUN pip3 install pytest
RUN pip3 install -r requirements.txt

COPY . .${workdir}

CMD PYTHONPATH=. python3 -m pytest
