# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster

ARG workdir=

WORKDIR ${workdir}

COPY requirements.txt requirements.txt
RUN pip3 install flake8
RUN pip3 install -r requirements.txt

COPY . .${workdir}

# warn if there are Python syntax errors or undefined names
CMD python3 -m flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
